name: Build and deploy .NET Core application to Web App lazy-blog-app
on:
  push:
    branches:
    - main
env:
  AZURE_WEBAPP_NAME: lazy-blog-app
  AZURE_WEBAPP_PACKAGE_PATH: Lazy.App\published
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x
  WORKING_DIRECTORY: src/Lazy.App
jobs:

  build:
    runs-on: windows-latest
    steps:
    - name: List current directory
      run: ls
    - name: Change working directory
      run: cd "${{env.WORKING_DIRECTORY}}"
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build  --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Test
      run: dotnet test  --no-build
    - name: Publish
      run: dotnet publish --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
    - name: Publish Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
  deploy:
    runs-on: windows-latest
    needs: build
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.lazy_blog_app_0635 }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
